# Generated by Django 5.1.1 on 2024-10-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichranker', '0002_auto_20241019_2040'),
    ]

    operations = [
    ]
