# Generated by Django 5.1.1 on 2024-10-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandwich_id', models.CharField(max_length=255, unique=True)),
                ('sandwich_name', models.CharField(default='', max_length=255)),
                ('average_rating', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('sandwich_image', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
