# Generated by Django 3.2.16 on 2023-01-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandwichranker', '0002_auto_20230128_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
